services:
  sentra:
    image: sentra_ros2
    build:
      context: .
      dockerfile: Dockerfile
    ssh:
      - default
    args:
      USERNAME: $USERNAME
      USER_UID: 1000
      USER_GID: 1000
    container_name: sentra_ros2
    environment:
      DISPLAY: $DISPLAY
      XAUTHORITY: $XAUTHORITY
      SSH_AUTH_SOCK: $SSH_AUTH_SOCK
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: all
      TERM: $TERM
      SHELL: $SHELL
    runtime: nvidia
    privileged: true
    restart: always
    devices:
      - /dev/bus/usb:/dev/bus/usb
    volumes:
      - $XAUTHORITY:$XAUTHORITY:rw
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - $SSH_AUTH_SOCK:$SSH_AUTH_SOCK