sentra_ros:
  ros__parameters:
    # General Parameters
    node_name: "sentra"
    init_check: true
    # Multimodal RAG Parameters
    rag:
      model: "siglip"
    # Data Parameters
    data_feed:
      # Visual Feed Parameters
      topic: "/camera/realsense/color/image_raw"
      frequency: 2.0