sentra_ros:
  ros__parameters:
    # General Parameters
    node_name: "sentra"
    init_check: true
    # Multimodal RAG Parameters
    rag:
      model: "siglip"
    # Data Parameters
    data_feed:
      # Visual Feed Parameters
      topic: "/camera/realsense/color/image_raw"
      frequency: 2.0
    # Embedding Parameters
    embedding:
      # Comparison Parameters
      top_k: 5
      min_similarity: 0.15
    # Output Parameters
    output:
      # Where to save the keyframes
      keyframes_path: "output/"
      # Should the keyframes be saved
      save_keyframes: true
      # Should the path be cleared on startup
      clear_on_startup: true